FROM golang:latest

WORKDIR /app

COPY . .

ENV ENV=PROD

ARG ADMIN_PASSWORD
RUN GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build \
    -ldflags "-X github.com/andrewwillette/andrewwillettedotcom/config.buildTimePassword=${ADMIN_PASSWORD}" \
    -o andrewwillettedotcom .

EXPOSE 80
EXPOSE 443

CMD ["./andrewwillettedotcom", "serve"]
