services:
  andrewwillette:
    build:
      context: .
    image: andrewwillette-dot-com:1.0
    environment:
      CONFIG_NAME: "app"
      ENV: "LOCAL"
    ports:
      - "80:80"
      - "443:443"
