version: '3'

services:
  andrewwillette-backend:
    build:
      context: ./backend
    image: andrewwillette-backend:1.0
    ports:
      - "9099:9099"
    volumes:
      - "~/db:/awillettebackend/db"

  andrewwillette-frontend:
    build:
      context: ./frontend
    image: andrewwillette-frontend:1.0
    ports:
      - "80:80"
    depends_on:
      - "andrewwillette-backend"
