FROM golang:latest

WORKDIR /app

COPY . .

ENV ENV=PROD

RUN GOARCH=amd64 GOOS=linux CGO_ENABLED=0 ENV=PROD go build -o andrewwillettedotcom .

EXPOSE 80
EXPOSE 443

CMD ["./andrewwillettedotcom", "serve"]
