version: '3'

services:
  andrewwillette:
    build:
      context: .
    image: andrewwillette-dot-com:1.0
    environment:
      ENV: "PROD"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /var/www/.cache
        target: /var/www/.cache
