services:
  andrewwillette:
    build:
      context: .
    image: andrewwillette-dot-com:1.0
    environment:
      ENV: "PROD"
      CONFIG_NAME: "prod"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # for persistening SSL cert across deploys
      - type: bind
        target: /var/www/.cache
        source: /var/www/.cache
      # for persisting logs across deploys
      - type: bind
        # see WORKDIR call in Dockerfile for target placement
        target: /app/logs
        source: /home/ubuntu
